name: "🐞 Computational Bug Report"
description: "Report an error or unexpected behavior in a script or software."
title: ": A brief description of the bug"
labels: ["bug", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Detailed reports help us resolve issues faster. Please search existing issues first to avoid duplicates.
  - type: input
    id: script-name
    attributes:
      label: "Script / Software Name"
      description: "What is the full path to the script or name of the software that has the bug?"
      placeholder: "e.g., /scripts/01_clean_data.py"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened? Please be as specific as possible."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide the exact steps to reproduce the error."
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: error-log
    attributes:
      label: "Error Log / Console Output"
      description: "Please paste the full, unedited error message or console output here."
      render: shell
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: "Operating System / Environment"
      description: "Where did you run into this issue?"
      options:
        - "Local Machine (macOS)"
        - "Local Machine (Windows)"
        - "Local Machine (Linux)"
        - "University HPC Cluster"
    validations:
      required: true