name: "✨ Feature or Analysis Request"
description: "Suggest an idea for a new feature, tool, or data analysis."
title: ": A brief, descriptive title"
labels: ["enhancement", "request"]
body:
  - type: markdown
    attributes:
      value: "Thank you for suggesting an improvement! Please provide the context below."
  - type: textarea
    id: problem-description
    attributes:
      label: "Is your request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      placeholder: "Describe the problem you're facing that this new feature would solve."
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "e.g., A new script that generates a summary plot of the results from..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context, mockups, or screenshots about the feature request here."